#!/bin/bash

(( $# == 1   )) || { echo "Usage: $(basename $0) NAME"; exit 1; }
[[ ! -e "$1" ]] || { echo "$1 aready exists"; exit 1; }

dir=~/.express-io

if [[ ! -d "$dir" ]]; then
  git clone git@github.com:bughou/express-io.git "$dir"
  git -C "$dir" remote rename origin express-io
fi

case "$1" in
  --update)
    git -C "$dir" pull express-io master
    ;;
  -*)
    echo unknow option "$1"
    ;;
  *)
    echo generating ...
    cp -r "$dir" "$1"
    echo done
    ;;
esac
